name: SoulLibrary
main: de.elia.api.Main
version: '3.0.1'
api-version: '1.20'
bootstrapper: de.elia.api.BootsTrapper
loader: de.elia.api.Loader
load-before:
  - name: SoulBossSystem
    bootstrap: true
  - name: SoulCommands
    bootstrap: false
  - name: SoulLeveling
    bootstrap: true
