name: SoulLibrary
main: de.elia.api.Main
version: '4.0.0'
api-version: '1.21'
bootstrapper: de.elia.api.BootsTrapper
loader: de.elia.api.Loader
load-before:
  - name: SoulBossSystem
    bootstrap: true
  - name: SoulCommands
    bootstrap: false
  - name: SoulLeveling
    bootstrap: true
  - name: SoulTransferPlugin
    bootstrap: true
